[package]
name = "builder"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
http = "1.1.0"
reqwest = "0.12.5"
tokio = { version = "1.38.0", features = ["full"]}
